version: 2.1
jobs:
  build_desa:
     docker:
       - image: circleci/node:14.15.5

     working_directory: ~/repo

     steps:
       - checkout

      # Download and cache dependencies
       - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

       - run: npm i

       - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      #- run: npm lint

   
       - run:
          name: Nuxt generate
          command: npm run generate

       - add_ssh_keys:
          fingerprints:
            - "b3:23:ab:7b:89:2b:79:58:2d:4b:b7:e7:02:30:f1:f3"

       - run:
          name: Accept ssh key
          command: ssh-keyscan -p 21609 -H 23.20.50.33 >> ~/.ssh/known_hosts

       - run:
          name: Delete previous build
          command: ssh ubuntu@23.20.50.33 -p 21609 rm -rf /var/www/reemper_landing/dist
       - run:
          name: Copy to server
          command: scp -P 21609 -r dist/ ubuntu@23.20.50.33:/var/www/reemper_landing/

       - run:
          name: Rename 200.html to index.html
          command: ssh ubuntu@23.20.50.33 -p 21609 mv /var/www/reemper_landing/dist/200.html /var/www/reemper_landing/dist/index.html
       - run:       
          name: Reload apache
          command: ssh ubuntu@23.20.50.33 -p 21609 sudo systemctl restart apache2

  build_prod:
    docker:
      - image: circleci/node:14.15.5

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      #- run: npm lint

      - run:
          name: Nuxt generate
          command: npm run generate

      - add_ssh_keys:
          fingerprints:
            - "82:02:e0:f5:23:26:eb:e6:66:77:fc:67:b0:2c:fd:13"

      - run:
          name: Accept ssh key
          command: ssh-keyscan -p 21609 -H 3.94.135.19 >> ~/.ssh/known_hosts

      - run:
          name: Delete previous build
          command: ssh ubuntu@3.94.135.19 -p 21609 rm -rf /var/www/reemper_landing/dist
      - run:
          name: Copy to server
          command: scp -P 21609 -r dist/ ubuntu@3.94.135.19:/var/www/reemper_landing/

      - run:
          name: Rename 200.html to index.html
          command: ssh ubuntu@3.94.135.19 -p 21609 mv /var/www/reemper_landing/dist/200.html /var/www/reemp_seekers/dist/index.html
      - run:       
          name: Reload apache
          command: ssh ubuntu@3.94.135.19 -p 21609 sudo systemctl restart apache2

workflows:
  version: 2.1
  build_desa:
    jobs:
      - build_desa:
          filters:
            branches:
              only: develop

  build_prod:
    jobs:
      - build_prod:
          filters:
            branches:
              only: master
